Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify",
            "name": "Formify",
            "summary": "Formify\u0020object",
            "url": "classes/App-Libraries-Formify-Formify.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020formify",
            "url": "classes/App-Libraries-Formify-Formify.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AcreateSection\u0028\u0029",
            "name": "createSection",
            "summary": "Creates\u0020a\u0020new\u0020Section\u0020object",
            "url": "classes/App-Libraries-Formify-Formify.html#method_createSection"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AsetDefaultTable\u0028\u0029",
            "name": "setDefaultTable",
            "summary": "Set\u0020attributes\u0020for\u0020dynamic\u0020form\u0020table,\u0020if\u0020not\u0020defined,\u0020default\u0020attributes\u0020will\u0020be\u0020used.",
            "url": "classes/App-Libraries-Formify-Formify.html#method_setDefaultTable"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AsetDefaultClass\u0028\u0029",
            "name": "setDefaultClass",
            "summary": "Sets\u0020default\u0020class\u0020attributes\u0020for\u0020form,\u0020if\u0020not\u0020defined,\u0020default\u0020classes\u0020will\u0020be\u0020used",
            "url": "classes/App-Libraries-Formify-Formify.html#method_setDefaultClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AsetDefaultSection\u0028\u0029",
            "name": "setDefaultSection",
            "summary": "Sets\u0020default\u0020class\u0020attributes\u0020for\u0020Section\u0020objects,\u0020if\u0020not\u0020defined,\u0020default\u0020classes\u0020will\u0020be\u0020used.",
            "url": "classes/App-Libraries-Formify-Formify.html#method_setDefaultSection"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generates\u0020and\u0020returns\u0020the\u0020form\u0020HTML",
            "url": "classes/App-Libraries-Formify-Formify.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AgenerateViewOnly\u0028\u0029",
            "name": "generateViewOnly",
            "summary": "Generates\u0020a\u0020view\u0020only\u0020version\u0020of\u0020the\u0020form",
            "url": "classes/App-Libraries-Formify-Formify.html#method_generateViewOnly"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AgetFileNames\u0028\u0029",
            "name": "getFileNames",
            "summary": "Returns\u0020array\u0020of\u0020file\u0020input\u0020names",
            "url": "classes/App-Libraries-Formify-Formify.html#method_getFileNames"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AgetFields\u0028\u0029",
            "name": "getFields",
            "summary": "Returns\u0020fields\u0020in\u0020form",
            "url": "classes/App-Libraries-Formify-Formify.html#method_getFields"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AaddName\u0028\u0029",
            "name": "addName",
            "summary": "Adds\u0020title\u0020and\u0020title_class\u0020HTML\u0020to\u0020form",
            "url": "classes/App-Libraries-Formify-Formify.html#method_addName"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Set\u0020the\u0020value\u0020of\u0020name",
            "url": "classes/App-Libraries-Formify-Formify.html#method_setName"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AsetAction\u0028\u0029",
            "name": "setAction",
            "summary": "Set\u0020the\u0020value\u0020of\u0020action",
            "url": "classes/App-Libraries-Formify-Formify.html#method_setAction"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AgetSection\u0028\u0029",
            "name": "getSection",
            "summary": "Get\u0020the\u0020value\u0020of\u0020sections",
            "url": "classes/App-Libraries-Formify-Formify.html#method_getSection"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AsetHideName\u0028\u0029",
            "name": "setHideName",
            "summary": "Set\u0020the\u0020value\u0020of\u0020hide_name",
            "url": "classes/App-Libraries-Formify-Formify.html#method_setHideName"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AsetNameTag\u0028\u0029",
            "name": "setNameTag",
            "summary": "Set\u0020the\u0020value\u0020of\u0020name_tag",
            "url": "classes/App-Libraries-Formify-Formify.html#method_setNameTag"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AsetNameClass\u0028\u0029",
            "name": "setNameClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020name_class",
            "url": "classes/App-Libraries-Formify-Formify.html#method_setNameClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AsetAttributes\u0028\u0029",
            "name": "setAttributes",
            "summary": "Set\u0020the\u0020value\u0020of\u0020attributes",
            "url": "classes/App-Libraries-Formify-Formify.html#method_setAttributes"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "Resets\u0020all\u0020attributes\u0020of\u0020the\u0020form\u0020object",
            "url": "classes/App-Libraries-Formify-Formify.html#method_reset"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AloadForm\u0028\u0029",
            "name": "loadForm",
            "summary": "Gets\u0020a\u0020form\u0020object\u0020based\u0020on\u0020form\u0020name",
            "url": "classes/App-Libraries-Formify-Formify.html#method_loadForm"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AgetFormField\u0028\u0029",
            "name": "getFormField",
            "summary": "Gets\u0020FormFieldModel\u0020to\u0020retrieve\u0020form\u0020data",
            "url": "classes/App-Libraries-Formify-Formify.html#method_getFormField"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003AgetUserForm\u0028\u0029",
            "name": "getUserForm",
            "summary": "Gets\u0020UserFormModel\u0020to\u0020retrieve\u0020data\u0020on\u0020userid\u0020and\u0020formid",
            "url": "classes/App-Libraries-Formify-Formify.html#method_getUserForm"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_name"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024action",
            "name": "action",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_action"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024sections",
            "name": "sections",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_sections"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024hide_name",
            "name": "hide_name",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_hide_name"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024name_tag",
            "name": "name_tag",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_name_tag"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024name_class",
            "name": "name_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_name_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024attributes",
            "name": "attributes",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_attributes"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024default_section",
            "name": "default_section",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_default_section"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024default_classes",
            "name": "default_classes",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_default_classes"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Formify\u003A\u003A\u0024default_table",
            "name": "default_table",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Formify.html#property_default_table"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Button",
            "name": "Button",
            "summary": "Represents\u0020a\u0020button\u0020Input\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-Button.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Button\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020Button\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-Button.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Button\u003A\u003AaddLabel\u0028\u0029",
            "name": "addLabel",
            "summary": "Adds\u0020label\u0020HTML\u0020element\u0020to\u0020button",
            "url": "classes/App-Libraries-Formify-Inputs-Button.html#method_addLabel"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Button\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generates\u0020button\u0020html",
            "url": "classes/App-Libraries-Formify-Inputs-Button.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Button\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "Sets\u0020value\u0020of\u0020button,\u0020used\u0020to\u0020override\u0020parent\u0020function",
            "url": "classes/App-Libraries-Formify-Inputs-Button.html#method_setValue"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Checkbox",
            "name": "Checkbox",
            "summary": "Represents\u0020a\u0020checkbox\u0020group\u0020Input\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-Checkbox.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Checkbox\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020Checkbox\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-Checkbox.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Checkbox\u003A\u003AaddCheckboxLabel\u0028\u0029",
            "name": "addCheckboxLabel",
            "summary": "Adds\u0020label\u0020HTML\u0020element\u0020to\u0020individual\u0020checkbox",
            "url": "classes/App-Libraries-Formify-Inputs-Checkbox.html#method_addCheckboxLabel"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Checkbox\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generates\u0020checkbox\u0020group\u0020HTML",
            "url": "classes/App-Libraries-Formify-Inputs-Checkbox.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Checkbox\u003A\u003AaddClass\u0028\u0029",
            "name": "addClass",
            "summary": "Adds\u0020class\u0020to\u0020all\u0020checkboxes",
            "url": "classes/App-Libraries-Formify-Inputs-Checkbox.html#method_addClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Checkbox\u003A\u003AsetInline\u0028\u0029",
            "name": "setInline",
            "summary": "Set\u0020the\u0020value\u0020of\u0020inline",
            "url": "classes/App-Libraries-Formify-Inputs-Checkbox.html#method_setInline"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Checkbox\u003A\u003AsetGroupLabelClass\u0028\u0029",
            "name": "setGroupLabelClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020group_label_class",
            "url": "classes/App-Libraries-Formify-Inputs-Checkbox.html#method_setGroupLabelClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Checkbox\u003A\u003A\u0024inline",
            "name": "inline",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Checkbox.html#property_inline"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Checkbox\u003A\u003A\u0024group_label_class",
            "name": "group_label_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Checkbox.html#property_group_label_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Dropdown",
            "name": "Dropdown",
            "summary": "Represents\u0020a\u0020dropdown\u0020Input\u0020object\u0020\u0028select\u0020HTML\u0020element\u0029",
            "url": "classes/App-Libraries-Formify-Inputs-Dropdown.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Dropdown\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020Dropdown\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-Dropdown.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Dropdown\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generates\u0020dropdown\u0020HTML",
            "url": "classes/App-Libraries-Formify-Inputs-Dropdown.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Dropdown\u003A\u003AaddClass\u0028\u0029",
            "name": "addClass",
            "summary": "Adds\u0020class\u0020to\u0020dropdown\u0020input\u0020element",
            "url": "classes/App-Libraries-Formify-Inputs-Dropdown.html#method_addClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Dropdown\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "Sets\u0020value\u0020of\u0020dropdown\u0020element\u0020HTML",
            "url": "classes/App-Libraries-Formify-Inputs-Dropdown.html#method_setValue"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Dropdown\u003A\u003AsetFloatingLabel\u0028\u0029",
            "name": "setFloatingLabel",
            "summary": "Set\u0020the\u0020value\u0020of\u0020floating_label",
            "url": "classes/App-Libraries-Formify-Inputs-Dropdown.html#method_setFloatingLabel"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Dropdown\u003A\u003A\u0024floating_label",
            "name": "floating_label",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Dropdown.html#property_floating_label"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable",
            "name": "DynamicTable",
            "summary": "Represents\u0020a\u0020table\u0020of\u0020inputs",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020DynamicTable\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AgenerateInputRow\u0028\u0029",
            "name": "generateInputRow",
            "summary": "Generates\u0020and\u0020returns\u0020HTML\u0020of\u0020each\u0020table\u0020row",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_generateInputRow"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generate\u0020table\u0020html",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AaddInputClass\u0028\u0029",
            "name": "addInputClass",
            "summary": "Adds\u0020class\u0020to\u0020all\u0020input\u0020element",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_addInputClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Get\u0020the\u0020value\u0020of\u0020id",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_getId"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Set\u0020the\u0020value\u0020of\u0020id",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_setId"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AsetHeaders\u0028\u0029",
            "name": "setHeaders",
            "summary": "Set\u0020the\u0020value\u0020of\u0020headers",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_setHeaders"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AsetMaxrows\u0028\u0029",
            "name": "setMaxrows",
            "summary": "Set\u0020the\u0020value\u0020of\u0020maxrows",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_setMaxrows"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AsetClass\u0028\u0029",
            "name": "setClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020class",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_setClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AsetAddButtonClass\u0028\u0029",
            "name": "setAddButtonClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020add_button_class",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_setAddButtonClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AsetAddButtonContent\u0028\u0029",
            "name": "setAddButtonContent",
            "summary": "Set\u0020the\u0020value\u0020of\u0020add_button_content",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_setAddButtonContent"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AsetDeleteButtonClass\u0028\u0029",
            "name": "setDeleteButtonClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020delete_button_class",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_setDeleteButtonClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003AsetDeleteButtonContent\u0028\u0029",
            "name": "setDeleteButtonContent",
            "summary": "Set\u0020the\u0020value\u0020of\u0020delete_button_content",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#method_setDeleteButtonContent"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#property_id"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#property_headers"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003A\u0024maxrows",
            "name": "maxrows",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#property_maxrows"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#property_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003A\u0024add_button_class",
            "name": "add_button_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#property_add_button_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003A\u0024add_button_content",
            "name": "add_button_content",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#property_add_button_content"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003A\u0024delete_button_class",
            "name": "delete_button_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#property_delete_button_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\DynamicTable\u003A\u003A\u0024delete_button_content",
            "name": "delete_button_content",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-DynamicTable.html#property_delete_button_content"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\FileInput",
            "name": "FileInput",
            "summary": "Represents\u0020a\u0020file\u0020Input\u0020Object",
            "url": "classes/App-Libraries-Formify-Inputs-FileInput.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\FileInput\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020FileInput\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-FileInput.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\FileInput\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generates\u0020file\u0020input\u0020HTML",
            "url": "classes/App-Libraries-Formify-Inputs-FileInput.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\FileInput\u003A\u003AgenerateViewOnly\u0028\u0029",
            "name": "generateViewOnly",
            "summary": "Generates\u0020a\u0020view\u0020only\u0020text\u0020field\u0020with\u0020file\u0020name",
            "url": "classes/App-Libraries-Formify-Inputs-FileInput.html#method_generateViewOnly"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\FileInput\u003A\u003AgetMultiple\u0028\u0029",
            "name": "getMultiple",
            "summary": "Returns\u0020true\u0020if\u0020multiple\u0020file\u0020uploads\u0020are\u0020enabled",
            "url": "classes/App-Libraries-Formify-Inputs-FileInput.html#method_getMultiple"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\FileInput\u003A\u003A\u0024multiple",
            "name": "multiple",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-FileInput.html#property_multiple"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\FileInput\u003A\u003A\u0024col_width",
            "name": "col_width",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-FileInput.html#property_col_width"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\FileInput\u003A\u003A\u0024wrapper_id",
            "name": "wrapper_id",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-FileInput.html#property_wrapper_id"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input",
            "name": "Input",
            "summary": "Parent\u0020class\u0020for\u0020all\u0020HTML\u0020input\u0020objects",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Parent\u0020constructor\u0020for\u0020input\u0020elements",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generate\u0020input\u0020element",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Returns\u0020name\u0020Attribute\u0020of\u0020input\u0020element\u0020HTML",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_getName"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Returns\u0020data\u0020array\u0020of\u0020input\u0020element",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_getData"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "Sets\u0020value\u0020of\u0020input\u0020element\u0020HTML",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_setValue"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AaddClass\u0028\u0029",
            "name": "addClass",
            "summary": "Adds\u0020class\u0020to\u0020input\u0020element",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_addClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AgetTooltipHtml\u0028\u0029",
            "name": "getTooltipHtml",
            "summary": "Gets\u0020tooltip\u0020HTML\u0020according\u0020to\u0020\u0024tooltip\u0020array",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_getTooltipHtml"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Set\u0020the\u0020value\u0020of\u0020name",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_setName"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AsetLabel\u0028\u0029",
            "name": "setLabel",
            "summary": "Set\u0020the\u0020value\u0020of\u0020label",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_setLabel"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "Set\u0020the\u0020value\u0020of\u0020description",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AsetLabelWidth\u0028\u0029",
            "name": "setLabelWidth",
            "summary": "Set\u0020the\u0020value\u0020of\u0020label_width",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_setLabelWidth"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AsetLabelClass\u0028\u0029",
            "name": "setLabelClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020label_class",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_setLabelClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AsetDescriptionClass\u0028\u0029",
            "name": "setDescriptionClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020description_class",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_setDescriptionClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003AsetTooltip\u0028\u0029",
            "name": "setTooltip",
            "summary": "Set\u0020the\u0020value\u0020of\u0020tooltip",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#method_setTooltip"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_data"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_name"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024label",
            "name": "label",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_label"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_description"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024horizontal",
            "name": "horizontal",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_horizontal"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024label_width",
            "name": "label_width",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_label_width"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024wrapper_tag",
            "name": "wrapper_tag",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_wrapper_tag"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024label_class",
            "name": "label_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_label_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024description_class",
            "name": "description_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_description_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Input\u003A\u003A\u0024tooltip",
            "name": "tooltip",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Input.html#property_tooltip"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio",
            "name": "Radio",
            "summary": "Represent\u0020a\u0020radio\u0020group\u0020Input\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020Radio\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio\u003A\u003AaddRadioLabel\u0028\u0029",
            "name": "addRadioLabel",
            "summary": "Adds\u0020label\u0020to\u0020individual\u0020label",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html#method_addRadioLabel"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generates\u0020radio\u0020group\u0020HTML",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio\u003A\u003AaddClass\u0028\u0029",
            "name": "addClass",
            "summary": "Adds\u0020class\u0020to\u0020every\u0020individual\u0020radio",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html#method_addClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "Sets\u0020checked\u0020radio",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html#method_setValue"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio\u003A\u003AsetInline\u0028\u0029",
            "name": "setInline",
            "summary": "Set\u0020the\u0020value\u0020of\u0020inline",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html#method_setInline"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio\u003A\u003AsetGroupLabelClass\u0028\u0029",
            "name": "setGroupLabelClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020group_label_class",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html#method_setGroupLabelClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio\u003A\u003A\u0024inline",
            "name": "inline",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html#property_inline"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\Radio\u003A\u003A\u0024group_label_class",
            "name": "group_label_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-Radio.html#property_group_label_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextArea",
            "name": "TextArea",
            "summary": "Represents\u0020a\u0020textarea\u0020Input\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-TextArea.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextArea\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020TextArea\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-TextArea.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextArea\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generates\u0020textarea\u0020HTML",
            "url": "classes/App-Libraries-Formify-Inputs-TextArea.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextArea\u003A\u003AsetFloatingLabel\u0028\u0029",
            "name": "setFloatingLabel",
            "summary": "Set\u0020the\u0020value\u0020of\u0020floating_label",
            "url": "classes/App-Libraries-Formify-Inputs-TextArea.html#method_setFloatingLabel"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextArea\u003A\u003A\u0024floating_label",
            "name": "floating_label",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-TextArea.html#property_floating_label"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextField",
            "name": "TextField",
            "summary": "Represents\u0020a\u0020standard\u0020Input\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-TextField.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextField\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020Textfield\u0020object",
            "url": "classes/App-Libraries-Formify-Inputs-TextField.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextField\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generates\u0020a\u0020standard\u0020input\u0020HTML",
            "url": "classes/App-Libraries-Formify-Inputs-TextField.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextField\u003A\u003AsetFloatingLabel\u0028\u0029",
            "name": "setFloatingLabel",
            "summary": "Set\u0020the\u0020value\u0020of\u0020floating_label",
            "url": "classes/App-Libraries-Formify-Inputs-TextField.html#method_setFloatingLabel"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs\\TextField\u003A\u003A\u0024floating_label",
            "name": "floating_label",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Inputs-TextField.html#property_floating_label"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section",
            "name": "Section",
            "summary": "Section\u0020object",
            "url": "classes/App-Libraries-Formify-Section.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020section",
            "url": "classes/App-Libraries-Formify-Section.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddName\u0028\u0029",
            "name": "addName",
            "summary": "Generate\u0020name\u0020and\u0020HTML",
            "url": "classes/App-Libraries-Formify-Section.html#method_addName"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddCheckbox\u0028\u0029",
            "name": "addCheckbox",
            "summary": "Adds\u0020a\u0020Checkbox\u0020group\u0020into\u0020the\u0020Section",
            "url": "classes/App-Libraries-Formify-Section.html#method_addCheckbox"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddRadio\u0028\u0029",
            "name": "addRadio",
            "summary": "Adds\u0020a\u0020Radio\u0020group\u0020into\u0020the\u0020Section",
            "url": "classes/App-Libraries-Formify-Section.html#method_addRadio"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddTextfield\u0028\u0029",
            "name": "addTextfield",
            "summary": "Adds\u0020a\u0020standard\u0020input\u0020into\u0020the\u0020Section",
            "url": "classes/App-Libraries-Formify-Section.html#method_addTextfield"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddDropdown\u0028\u0029",
            "name": "addDropdown",
            "summary": "Adds\u0020a\u0020dropdown\u0020into\u0020the\u0020Section",
            "url": "classes/App-Libraries-Formify-Section.html#method_addDropdown"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddTextarea\u0028\u0029",
            "name": "addTextarea",
            "summary": "Adds\u0020a\u0020TextArea\u0020into\u0020the\u0020Section",
            "url": "classes/App-Libraries-Formify-Section.html#method_addTextarea"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddFileInput\u0028\u0029",
            "name": "addFileInput",
            "summary": "Adds\u0020a\u0020File\u0020Input\u0020into\u0020the\u0020Section",
            "url": "classes/App-Libraries-Formify-Section.html#method_addFileInput"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddButton\u0028\u0029",
            "name": "addButton",
            "summary": "Adds\u0020a\u0020Button\u0020into\u0020the\u0020section",
            "url": "classes/App-Libraries-Formify-Section.html#method_addButton"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddDynamicTable\u0028\u0029",
            "name": "addDynamicTable",
            "summary": "Adds\u0020a\u0020Dynamic\u0020Table\u0020into\u0020the\u0020section",
            "url": "classes/App-Libraries-Formify-Section.html#method_addDynamicTable"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generate\u0020section\u0020HTML",
            "url": "classes/App-Libraries-Formify-Section.html#method_generate"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AaddHtml\u0028\u0029",
            "name": "addHtml",
            "summary": "Adds\u0020custom\u0020HTML\u0020to\u0020the\u0020Section",
            "url": "classes/App-Libraries-Formify-Section.html#method_addHtml"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003Alog_warning_label_width\u0028\u0029",
            "name": "log_warning_label_width",
            "summary": "Logs\u0020warning\u0020if\u0020\u0024label_width\u0020is\u0020set\u0020to\u0020more\u0020than\u002012\u0020or\u0020less\u0020than\u00200",
            "url": "classes/App-Libraries-Formify-Section.html#method_log_warning_label_width"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003Alog_warning_col_width\u0028\u0029",
            "name": "log_warning_col_width",
            "summary": "Logs\u0020warning\u0020if\u0020\u0024col_width\u0020is\u0020set\u0020to\u0020more\u0020than\u002012\u0020or\u0020less\u0020than\u00200",
            "url": "classes/App-Libraries-Formify-Section.html#method_log_warning_col_width"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003Alog_warning_floating_label\u0028\u0029",
            "name": "log_warning_floating_label",
            "summary": "Logs\u0020warning\u0020if\u0020\u0024label_width\u0020is\u0020set\u0020to\u0020less\u0020than\u002012\u0020and\u0020\u0024floating_label\u0020is\u0020set\u0020to\u0020true\u0020at\u0020the\u0020same\u0020time",
            "url": "classes/App-Libraries-Formify-Section.html#method_log_warning_floating_label"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AgetInputs\u0028\u0029",
            "name": "getInputs",
            "summary": "Get\u0020the\u0020value\u0020of\u0020inputs",
            "url": "classes/App-Libraries-Formify-Section.html#method_getInputs"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Get\u0020the\u0020value\u0020of\u0020name",
            "url": "classes/App-Libraries-Formify-Section.html#method_getName"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Set\u0020the\u0020value\u0020of\u0020name",
            "url": "classes/App-Libraries-Formify-Section.html#method_setName"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Get\u0020the\u0020value\u0020of\u0020id",
            "url": "classes/App-Libraries-Formify-Section.html#method_getId"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Set\u0020the\u0020value\u0020of\u0020id",
            "url": "classes/App-Libraries-Formify-Section.html#method_setId"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "Set\u0020the\u0020value\u0020of\u0020description",
            "url": "classes/App-Libraries-Formify-Section.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AsetTitleWidth\u0028\u0029",
            "name": "setTitleWidth",
            "summary": "Set\u0020the\u0020value\u0020of\u0020title_width",
            "url": "classes/App-Libraries-Formify-Section.html#method_setTitleWidth"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AsetTitleTag\u0028\u0029",
            "name": "setTitleTag",
            "summary": "Set\u0020the\u0020value\u0020of\u0020title_tag",
            "url": "classes/App-Libraries-Formify-Section.html#method_setTitleTag"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AsetTitleClass\u0028\u0029",
            "name": "setTitleClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020title_class",
            "url": "classes/App-Libraries-Formify-Section.html#method_setTitleClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AsetDescriptionClass\u0028\u0029",
            "name": "setDescriptionClass",
            "summary": "Set\u0020the\u0020value\u0020of\u0020description_class",
            "url": "classes/App-Libraries-Formify-Section.html#method_setDescriptionClass"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AsetHideName\u0028\u0029",
            "name": "setHideName",
            "summary": "Set\u0020the\u0020value\u0020of\u0020hide_name",
            "url": "classes/App-Libraries-Formify-Section.html#method_setHideName"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003AsetHideBreak\u0028\u0029",
            "name": "setHideBreak",
            "summary": "Set\u0020the\u0020value\u0020of\u0020hide_break",
            "url": "classes/App-Libraries-Formify-Section.html#method_setHideBreak"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024inputs",
            "name": "inputs",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_inputs"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_name"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_id"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_description"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024title_width",
            "name": "title_width",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_title_width"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024title_tag",
            "name": "title_tag",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_title_tag"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024title_class",
            "name": "title_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_title_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024description_class",
            "name": "description_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_description_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024default_classes",
            "name": "default_classes",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_default_classes"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024default_table",
            "name": "default_table",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_default_table"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024section_class",
            "name": "section_class",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_section_class"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024hide_name",
            "name": "hide_name",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_hide_name"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Section\u003A\u003A\u0024hide_break",
            "name": "hide_break",
            "summary": "",
            "url": "classes/App-Libraries-Formify-Section.html#property_hide_break"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify",
            "name": "Formify",
            "summary": "",
            "url": "namespaces/app-libraries-formify.html"
        },                {
            "fqsen": "\\App\\Libraries",
            "name": "Libraries",
            "summary": "",
            "url": "namespaces/app-libraries.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Libraries\\Formify\\Inputs",
            "name": "Inputs",
            "summary": "",
            "url": "namespaces/app-libraries-formify-inputs.html"
        }            ]
);
